/* 현장 작업판: 수동 작업 + 발주별 일괄 출고 */
const v14style=document.createElement('style');v14style.textContent=`.work-head{display:flex;justify-content:space-between;align-items:center;margin:22px 0 8px}.work-head h3{margin:0}.work-add,.bulk-button{border:1px solid #cbdcd3;border-radius:9px;padding:8px 10px;background:#fff;color:#235342;font:inherit;font-size:.86rem;font-weight:800}.manual-task{display:grid;grid-template-columns:22px minmax(0,1fr) auto auto;align-items:center;gap:8px;padding:12px 14px;background:#fff;border:1px solid #d9e6df;border-radius:12px;margin:6px 0}.manual-task .task-text{min-width:0;overflow-wrap:anywhere}.manual-task small{display:block;color:#60766d;margin-top:3px}.manual-task button{border:0;background:transparent;color:#597268;font:inherit;white-space:nowrap}.manual-task .task-amount{font-weight:800;color:#123c39}.bulk-button{margin:8px 0}.bulk-line{padding:11px 0;border-bottom:1px solid #e4ece7}.bulk-line:last-child{border:0}.bulk-line label{display:grid;grid-template-columns:20px 1fr 95px;gap:8px;align-items:center}.bulk-line input[type=number]{width:100%;padding:8px;border:1px solid #cbdcd3;border-radius:8px;font:inherit}.bulk-line small{display:block;color:#60766d;margin:4px 0 0 28px}.bulk-total{margin:12px 0;color:#60766d}.manual-form input{width:100%;padding:11px;border:1px solid #cbdcd3;border-radius:9px;font:inherit;box-sizing:border-box}.task-two{display:grid;grid-template-columns:1fr 1fr;gap:10px}.task-hidden{display:none!important}`;document.head.append(v14style);
document.body.insertAdjacentHTML('beforeend',`<dialog id="bulkDialog" class="dialog"><form id="bulkForm"><div class="dialog-head"><h2 id="bulkTitle">일괄 출고</h2><button class="close" type="button" data-close>×</button></div><p id="bulkNotice" class="info"></p><div id="bulkLines"></div><p id="bulkTotal" class="bulk-total"></p><div class="actions"><button class="secondary" type="button" data-close>취소</button><button class="primary" type="submit">선택 품목 출고 처리</button></div></form></dialog><dialog id="taskDialog" class="dialog"><form id="taskForm" class="manual-form"><div class="dialog-head"><h2 id="taskTitle">수동 작업 추가</h2><button class="close" type="button" data-close>×</button></div><label>작업 내용<input id="taskText" required placeholder="예: 분진기 청소, 택배 접수"></label><div id="taskQuantityFields" class="task-two"><label>목표 수량<input id="taskTarget" type="number" min="0" step="0.01" placeholder="수량 작업일 때만 입력"></label><label>완료 수량<input id="taskDoneQty" type="number" min="0" step="0.01" value="0"></label></div><label>단위<input id="taskUnit" placeholder="예: 개, 통, 건"></label><div class="actions"><button class="secondary" type="button" data-close>취소</button><button class="primary" type="submit">저장</button></div></form></dialog>`);
data.manualTasks??=[];
function taskHtml(kind){let ts=data.manualTasks.filter(t=>t.kind===kind&&!t.done&&(!n(t.target)||n(t.doneQty)<n(t.target)));return ts.map(t=>`<article class="manual-task"><input type="checkbox" data-task-done="${t.id}"><span class="task-text"><strong>${esc(t.text||'수동 작업')}</strong>${n(t.target)?`<small>완료 ${q(t.doneQty||0)} / ${q(t.target)}${esc(t.unit||'')}</small>`:''}</span>${n(t.target)?`<button class="task-amount" type="button" data-task-fill="${t.id}">완료 입력</button>`:''}<button type="button" data-task-edit="${t.id}">수정</button><button type="button" data-task-remove="${t.id}">삭제</button></article>`).join('')}
function workSection(kind,title){return `<div class="work-head"><h3 class="priority-title">${title}</h3><button class="work-add" data-task-add="${kind}">+ 수동 작업</button></div>${taskHtml(kind)}`}
const priorPriority14=priority;priority=()=>{priorPriority14();let p=$('#priorityList');let old=[...p.querySelectorAll('.work-head,.manual-task')];old.forEach(x=>x.remove());let heads=[...p.querySelectorAll('.priority-title')];let prodHead=heads.find(x=>x.textContent.includes('생산 예정'));let prioHead=heads.find(x=>x.textContent.includes('우선 처리'));if(prodHead){prodHead.textContent='오늘 / 이번 주 생산 예정';prodHead.insertAdjacentHTML('afterend',taskHtml('production'));prodHead.insertAdjacentHTML('afterend','<button class="work-add" data-task-add="production">+ 수동 작업</button>')}if(prioHead){prioHead.insertAdjacentHTML('afterend',taskHtml('priority'));prioHead.insertAdjacentHTML('afterend','<button class="work-add" data-task-add="priority">+ 수동 작업</button>')}};
const priorOrderHtml14=orderHtml;orderHtml=(o,dash=false)=>priorOrderHtml14(o,dash).replace(/(<p class="muted">[\s\S]*?<\/p>)?/,`$1<button class="bulk-button" data-bulk-order="${o.id}">일괄 출고</button>`);
function openBulk(oid){let o=data.orders.find(x=>x.id===oid),rows=o.lines.filter(l=>n(l.quantity)>n(l.shipped)).map(l=>{let p=data.products.find(x=>x.id===l.productId),left=n(l.quantity)-n(l.shipped),possible=Math.min(left,Math.max(0,stock(p)));return {l,p,left,possible}});$('#bulkDialog').dataset.order=oid;$('#bulkTitle').textContent=`${o.company} 일괄 출고`;$('#bulkNotice').textContent='출고할 품목만 체크하세요. 수량은 필요하면 직접 줄여 부분 출고할 수 있습니다.';$('#bulkLines').innerHTML=rows.length?rows.map(({l,p,left,possible})=>`<div class="bulk-line"><label><input type="checkbox" data-bulk-check="${l.id}" ${possible>0?'checked':''} ${possible<=0?'disabled':''}><span><strong>${esc(l.name)}</strong> · ${esc(l.spec)}</span><input type="number" data-bulk-qty="${l.id}" min="0" max="${possible}" step="0.01" value="${possible}"></label><small>발주 잔량 ${q(left)}${l.unit} · 출고 가능 ${q(possible)}${l.unit}</small></div>`).join(''):'<div class="empty">이미 모두 출고된 발주입니다.</div>';show('#bulkDialog')}
function updateBulkTotal(){let count=0;$$('#bulkLines input[data-bulk-check]').forEach(c=>{if(c.checked&&n($(`[data-bulk-qty="${c.dataset.bulkCheck}"]`).value)>0)count++});$('#bulkTotal').textContent=count?`${count}개 품목을 출고 처리합니다.`:'출고할 품목을 선택하세요.'}
$('#bulkLines').addEventListener('input',updateBulkTotal);$('#bulkLines').addEventListener('change',updateBulkTotal);
$('#bulkForm').onsubmit=e=>{e.preventDefault();let o=data.orders.find(x=>x.id===$('#bulkDialog').dataset.order),actions=[];$$('#bulkLines input[data-bulk-check]').forEach(c=>{if(!c.checked)return;let l=o.lines.find(x=>x.id===c.dataset.bulkCheck),qty=n($(`[data-bulk-qty="${l.id}"]`).value),p=data.products.find(x=>x.id===l.productId);if(qty>0&&qty<=stock(p)&&qty<=n(l.quantity)-n(l.shipped))actions.push({l,p,qty})});if(!actions.length)return toast('출고할 품목을 선택하세요.');let text=actions.map(x=>`${x.l.name} ${q(x.qty)}${x.l.unit}`).join(', ');if(!confirm(`${o.company} 발주에 다음 품목을 출고 처리할까요?\n${text}`))return;let before=JSON.stringify(data);actions.forEach(x=>{x.l.shipped=n(x.l.shipped)+x.qty;x.p.shipped=n(x.p.shipped)+x.qty;record(x.p,`${o.company} 일괄 출고 -${q(x.qty)}${x.l.unit}`)});hide('#bulkDialog');save();undo(before,`${o.company} ${actions.length}개 품목 출고 처리`)};
let taskMode='',editingTask='';function openTask(kind,id=''){taskMode=kind;editingTask=id;let t=data.manualTasks.find(x=>x.id===id);$('#taskTitle').textContent=id?'수동 작업 수정':'수동 작업 추가';$('#taskText').value=t?.text||'';$('#taskTarget').value=t?.target||'';$('#taskDoneQty').value=t?.doneQty||0;$('#taskUnit').value=t?.unit||'';show('#taskDialog')}
$('#taskForm').onsubmit=e=>{e.preventDefault();let text=$('#taskText').value.trim(),target=n($('#taskTarget').value),doneQty=n($('#taskDoneQty').value),unit=$('#taskUnit').value.trim();if(!text)return;let t=data.manualTasks.find(x=>x.id===editingTask);let values={text,target,doneQty,unit,done:target>0?doneQty>=target:false};if(t)Object.assign(t,values);else data.manualTasks.unshift({id:id(),kind:taskMode,...values});hide('#taskDialog');save();toast(target&&doneQty>=target?'목표 수량을 채워 작업 목록에서 제거했습니다.':'수동 작업을 저장했습니다.')};
function fillTask(id){let t=data.manualTasks.find(x=>x.id===id),v=prompt(`${t.text}\n현재 ${q(t.doneQty||0)} / 목표 ${q(t.target)}${t.unit||''}\n완료 수량을 입력하세요.`,t.doneQty||0);if(v===null)return;let next=n(v);if(next<0)return;t.doneQty=next;t.done=next>=n(t.target);save();toast(t.done?'목표 수량을 채워 작업 목록에서 제거했습니다.':'완료 수량을 반영했습니다.')}
document.addEventListener('click',e=>{let d=e.target.dataset;if(d.bulkOrder)openBulk(d.bulkOrder);if(d.taskAdd)openTask(d.taskAdd);if(d.taskEdit)openTask('',d.taskEdit);if(d.taskFill)fillTask(d.taskFill);if(d.taskRemove){data.manualTasks=data.manualTasks.filter(t=>t.id!==d.taskRemove);save()}if(d.taskDone){let t=data.manualTasks.find(x=>x.id===d.taskDone);t.done=e.target.checked;save()}});
const priorRender14=render;render=()=>{priorRender14();};render();
