/* 현장 작업판: 수동 작업 + 발주별 일괄 출고 */
const v14style=document.createElement('style');v14style.textContent=`.work-head{display:flex;justify-content:space-between;align-items:center;margin:18px 0 8px}.work-head h3{margin:0}.work-add,.bulk-button{border:1px solid #cbdcd3;border-radius:9px;padding:8px 10px;background:#fff;color:#235342;font:inherit;font-size:.86rem;font-weight:800}.manual-task{display:flex;align-items:center;gap:9px;padding:11px 13px;background:#fff;border:1px solid #d9e6df;border-radius:12px;margin:6px 0}.manual-task.done{text-decoration:line-through;opacity:.55}.manual-task .task-text{flex:1}.manual-task button{border:0;background:transparent;color:#597268;font:inherit}.bulk-button{margin:8px 0}.bulk-line{padding:11px 0;border-bottom:1px solid #e4ece7}.bulk-line:last-child{border:0}.bulk-line label{display:grid;grid-template-columns:20px 1fr 95px;gap:8px;align-items:center}.bulk-line input[type=number]{width:100%;padding:8px;border:1px solid #cbdcd3;border-radius:8px;font:inherit}.bulk-line small{display:block;color:#60766d;margin:4px 0 0 28px}.bulk-total{margin:12px 0;color:#60766d}.manual-form input{width:100%;padding:11px;border:1px solid #cbdcd3;border-radius:9px;font:inherit;box-sizing:border-box}`;document.head.append(v14style);
document.body.insertAdjacentHTML('beforeend',`<dialog id="bulkDialog" class="dialog"><form id="bulkForm"><div class="dialog-head"><h2 id="bulkTitle">일괄 출고</h2><button class="close" type="button" data-close>×</button></div><p id="bulkNotice" class="info"></p><div id="bulkLines"></div><p id="bulkTotal" class="bulk-total"></p><div class="actions"><button class="secondary" type="button" data-close>취소</button><button class="primary" type="submit">선택 품목 출고 처리</button></div></form></dialog><dialog id="taskDialog" class="dialog"><form id="taskForm" class="manual-form"><div class="dialog-head"><h2 id="taskTitle">수동 작업 추가</h2><button class="close" type="button" data-close>×</button></div><label>작업 내용<input id="taskText" required placeholder="예: 택배 접수, 지그 확인"></label><div class="actions"><button class="secondary" type="button" data-close>취소</button><button class="primary" type="submit">저장</button></div></form></dialog>`);
data.manualTasks??=[];
function taskHtml(kind){let ts=data.manualTasks.filter(t=>t.kind===kind);return ts.map(t=>`<article class="manual-task ${t.done?'done':''}"><input type="checkbox" data-task-done="${t.id}" ${t.done?'checked':''}><span class="task-text">${esc(t.text)}</span><button type="button" data-task-edit="${t.id}">수정</button><button type="button" data-task-remove="${t.id}">삭제</button></article>`).join('')}
function workSection(kind,title){return `<div class="work-head"><h3 class="priority-title">${title}</h3><button class="work-add" data-task-add="${kind}">+ 수동 작업</button></div>${taskHtml(kind)}`}
const priorPriority14=priority;priority=()=>{priorPriority14();let p=$('#priorityList');p.insertAdjacentHTML('afterbegin',workSection('priority','오늘 / 이번 주 우선 처리'));p.insertAdjacentHTML('afterbegin',workSection('production','오늘 생산 예정'))};
const priorOrderHtml14=orderHtml;orderHtml=(o,dash=false)=>priorOrderHtml14(o,dash).replace(/(<p class="muted">[\s\S]*?<\/p>)?/,`$1<button class="bulk-button" data-bulk-order="${o.id}">일괄 출고</button>`);
function openBulk(oid){let o=data.orders.find(x=>x.id===oid),rows=o.lines.filter(l=>n(l.quantity)>n(l.shipped)).map(l=>{let p=data.products.find(x=>x.id===l.productId),left=n(l.quantity)-n(l.shipped),possible=Math.min(left,Math.max(0,stock(p)));return {l,p,left,possible}});$('#bulkDialog').dataset.order=oid;$('#bulkTitle').textContent=`${o.company} 일괄 출고`;$('#bulkNotice').textContent='출고할 품목만 체크하세요. 수량은 필요하면 직접 줄여 부분 출고할 수 있습니다.';$('#bulkLines').innerHTML=rows.length?rows.map(({l,p,left,possible})=>`<div class="bulk-line"><label><input type="checkbox" data-bulk-check="${l.id}" ${possible>0?'checked':''} ${possible<=0?'disabled':''}><span><strong>${esc(l.name)}</strong> · ${esc(l.spec)}</span><input type="number" data-bulk-qty="${l.id}" min="0" max="${possible}" step="0.01" value="${possible}"></label><small>발주 잔량 ${q(left)}${l.unit} · 출고 가능 ${q(possible)}${l.unit}</small></div>`).join(''):'<div class="empty">이미 모두 출고된 발주입니다.</div>';show('#bulkDialog')}
function updateBulkTotal(){let count=0;$$('#bulkLines input[data-bulk-check]').forEach(c=>{if(c.checked&&n($(`[data-bulk-qty="${c.dataset.bulkCheck}"]`).value)>0)count++});$('#bulkTotal').textContent=count?`${count}개 품목을 출고 처리합니다.`:'출고할 품목을 선택하세요.'}
$('#bulkLines').addEventListener('input',updateBulkTotal);$('#bulkLines').addEventListener('change',updateBulkTotal);
$('#bulkForm').onsubmit=e=>{e.preventDefault();let o=data.orders.find(x=>x.id===$('#bulkDialog').dataset.order),actions=[];$$('#bulkLines input[data-bulk-check]').forEach(c=>{if(!c.checked)return;let l=o.lines.find(x=>x.id===c.dataset.bulkCheck),qty=n($(`[data-bulk-qty="${l.id}"]`).value),p=data.products.find(x=>x.id===l.productId);if(qty>0&&qty<=stock(p)&&qty<=n(l.quantity)-n(l.shipped))actions.push({l,p,qty})});if(!actions.length)return toast('출고할 품목을 선택하세요.');let text=actions.map(x=>`${x.l.name} ${q(x.qty)}${x.l.unit}`).join(', ');if(!confirm(`${o.company} 발주에 다음 품목을 출고 처리할까요?\n${text}`))return;let before=JSON.stringify(data);actions.forEach(x=>{x.l.shipped=n(x.l.shipped)+x.qty;x.p.shipped=n(x.p.shipped)+x.qty;record(x.p,`${o.company} 일괄 출고 -${q(x.qty)}${x.l.unit}`)});hide('#bulkDialog');save();undo(before,`${o.company} ${actions.length}개 품목 출고 처리`)};
let taskMode='',editingTask='';function openTask(kind,id=''){taskMode=kind;editingTask=id;let t=data.manualTasks.find(x=>x.id===id);$('#taskTitle').textContent=id?'수동 작업 수정':'수동 작업 추가';$('#taskText').value=t?.text||'';show('#taskDialog')}
$('#taskForm').onsubmit=e=>{e.preventDefault();let text=$('#taskText').value.trim();if(!text)return;let t=data.manualTasks.find(x=>x.id===editingTask);if(t)t.text=text;else data.manualTasks.unshift({id:id(),kind:taskMode,text,done:false});hide('#taskDialog');save();toast('수동 작업을 저장했습니다.')};
document.addEventListener('click',e=>{let d=e.target.dataset;if(d.bulkOrder)openBulk(d.bulkOrder);if(d.taskAdd)openTask(d.taskAdd);if(d.taskEdit)openTask('',d.taskEdit);if(d.taskRemove){data.manualTasks=data.manualTasks.filter(t=>t.id!==d.taskRemove);save()}if(d.taskDone){let t=data.manualTasks.find(x=>x.id===d.taskDone);t.done=e.target.checked;save()}});
const priorRender14=render;render=()=>{priorRender14();};render();
