(() => {
  const UX=window.CivilUX; if(!UX)return;
  UX.setSelection=new Set(); UX.editingSetId=null;
  UX.weakIds=()=>{const a=store.get('uxAttempts',{}),out=[];Object.entries(a).forEach(([id,arr])=>{const q=UX.byId(id);if(!q||UX.isMemorized(q)||!Array.isArray(arr)||arr.length<3)return;const last=arr.slice(-3);if(last.filter(x=>!x.correct).length>=2)out.push(id);});return out;};
  UX.setupSetFilters=()=>{const max=Math.max(1,...UX.unique().map(q=>Number(q.frequency||1)));UX.q('#setFrequencyFilter').innerHTML='<option value="1">출제빈도 전체</option>'+Array.from({length:Math.max(0,max-1)},(_,i)=>i+2).map(n=>`<option value="${n}">${n}회 이상</option>`).join('');const ys=[...new Set(state.questions.map(q=>UX.yearCode(q.round)))].sort((a,b)=>Number(b)-Number(a));UX.q('#setYearFilter').innerHTML='<option value="all">연도 전체</option>'+ys.map(y=>`<option value="${UX.esc(y)}">${UX.fullYear(y)}년</option>`).join('');};
  UX.filteredSetQuestions=()=>{const min=Number(UX.q('#setFrequencyFilter').value||1),status=UX.q('#setStatusFilter').value,year=UX.q('#setYearFilter').value,search=UX.q('#setSearchInput').value.trim().toLowerCase();return UX.unique().filter(q=>{if(Number(q.frequency||1)<min)return false;if(year!=='all'&&!UX.appearances(UX.idOf(q)).some(r=>UX.yearCode(r)===year))return false;if(search&&!`${q.question} ${q.answer}`.toLowerCase().includes(search))return false;if(status==='favorite'&&!UX.isFavorite(q))return false;if(status==='wrong'&&!UX.isWrong(q))return false;if(status==='memorized'&&!UX.isMemorized(q))return false;if(status==='normal'&&(UX.isFavorite(q)||UX.isWrong(q)||UX.isMemorized(q)))return false;return true;}).sort((a,b)=>Number(b.frequency||1)-Number(a.frequency||1)||Number(a.id)-Number(b.id));};
  UX.renderSetList=()=>{const list=UX.filteredSetQuestions();UX.q('#setQuestionList').innerHTML=list.length?list.map(q=>{const id=UX.idOf(q);return `<label class="ux-question-option"><input type="checkbox" data-ux-set-id="${UX.esc(id)}" ${UX.setSelection.has(id)?'checked':''}><span class="ux-qtext">${UX.isFavorite(q)?'<span class="ux-star">★</span> ':''}${UX.esc(q.question)}</span><span class="ux-qmeta">${Number(q.frequency||1)}회<br>${UX.appearances(id).slice(0,2).join(', ')}</span></label>`;}).join(''):'<div class="ux-empty">조건에 맞는 문제가 없습니다.</div>';UX.q('#setSelectedCount').textContent=`선택 ${UX.setSelection.size}문제`;};
  UX.syncSetSelection=()=>{UX.qa('#setQuestionList [data-ux-set-id]').forEach(x=>x.checked?UX.setSelection.add(x.dataset.uxSetId):UX.setSelection.delete(x.dataset.uxSetId));UX.q('#setSelectedCount').textContent=`선택 ${UX.setSelection.size}문제`;};
  UX.openSetModal=(set=null)=>{UX.editingSetId=set?.id||null;UX.setSelection=new Set((set?.questionIds||[]).map(String));UX.q('#setNameInput').value=set?.name||'';UX.q('#setSearchInput').value='';UX.q('#setFrequencyFilter').value='1';UX.q('#setStatusFilter').value='all';UX.q('#setYearFilter').value='all';UX.q('#setModalTitle').textContent=set?'학습세트 수정':'학습세트 만들기';UX.q('#setModal').classList.remove('hidden');UX.renderSetList();};
  UX.saveSet=()=>{UX.syncSetSelection();const name=UX.q('#setNameInput').value.trim();if(!name)return alert('학습세트 이름을 입력해 주세요.');if(!UX.setSelection.size)return alert('문제를 1개 이상 선택해 주세요.');const sets=store.get('studySets2',[]);if(UX.editingSetId){const s=sets.find(x=>x.id===UX.editingSetId);if(s){s.name=name;s.questionIds=[...UX.setSelection];s.updatedAt=new Date().toISOString();}}else sets.push({id:`set-${Date.now()}`,name,questionIds:[...UX.setSelection],createdAt:new Date().toISOString()});store.set('studySets2',sets);UX.q('#setModal').classList.add('hidden');UX.renderSets();};
  UX.renderSets=()=>{const sets=store.get('studySets2',[]),weak=UX.weakIds();UX.q('#panelTitle').textContent='나만의 학습세트';UX.q('#panelContent').innerHTML=`<div class="card ux-panel-card"><div class="ux-set-head"><div><strong>⚡ 취약문제</strong><div class="ux-rule">최소 3회 이상 풀고, 최근 3회 중 2회 이상 틀린 문제</div></div><span class="ux-badge">${weak.length}문제</span></div>${weak.length?`<div class="ux-weak-row"><div class="muted">${weak.slice(0,3).map(id=>{const q=UX.byId(id),a=(store.get('uxAttempts',{})[id]||[]).slice(-3).map(x=>x.correct?'O':'X').join(' ');return `${UX.esc(q.question.slice(0,26))} · ${a}`;}).join('<br>')}${weak.length>3?'<br>…':''}</div><div class="ux-row-actions"><button data-ux-run-weak>취약문제 풀기</button></div></div>`:'<div class="ux-empty">아직 취약문제로 판정된 문제가 없습니다.</div>'}</div><div class="card ux-panel-card"><div class="ux-set-head"><strong>내 학습세트</strong><button class="ux-small-button" data-ux-new-set>+ 새 세트</button></div>${sets.length?sets.map(s=>`<div class="ux-set-row"><div class="ux-set-head"><h3>${UX.esc(s.name)}</h3><span class="ux-badge">${s.questionIds.length}문제</span></div><div class="ux-row-actions"><button data-ux-run-set="${UX.esc(s.id)}">풀기</button><button data-ux-edit-set="${UX.esc(s.id)}">수정</button><button class="ux-danger" data-ux-delete-set="${UX.esc(s.id)}">삭제</button></div></div>`).join(''):'<div class="ux-empty">아직 만든 학습세트가 없습니다.<br>즐겨찾기·오답·출제빈도·연도 필터로 원하는 문제만 직접 골라 만들 수 있습니다.</div>'}</div>`;};

  document.addEventListener('click',e=>{if(e.target.closest('[data-ux-new-set]'))UX.openSetModal();const run=e.target.closest('[data-ux-run-set]');if(run){const s=store.get('studySets2',[]).find(x=>x.id===run.dataset.uxRunSet);if(s)UX.start('set',s.questionIds.map(UX.byId).filter(Boolean),s.name);}const edit=e.target.closest('[data-ux-edit-set]');if(edit){const s=store.get('studySets2',[]).find(x=>x.id===edit.dataset.uxEditSet);if(s)UX.openSetModal(s);}const del=e.target.closest('[data-ux-delete-set]');if(del&&confirm('이 학습세트를 삭제할까요?')){store.set('studySets2',store.get('studySets2',[]).filter(s=>s.id!==del.dataset.uxDeleteSet));UX.renderSets();}if(e.target.closest('[data-ux-run-weak]')){const list=UX.weakIds().map(UX.byId).filter(Boolean);if(list.length)UX.start('weak',list,'취약문제');}});
  document.addEventListener('change',e=>{if(e.target.matches('[data-ux-set-id]'))UX.syncSetSelection();if(e.target.matches('#setFrequencyFilter,#setStatusFilter,#setYearFilter')){UX.syncSetSelection();UX.renderSetList();}});
  UX.q('#setSearchInput').addEventListener('input',()=>{UX.syncSetSelection();UX.renderSetList();});
  UX.q('#closeSetModal').onclick=()=>UX.q('#setModal').classList.add('hidden');UX.q('#saveSetButton').onclick=UX.saveSet;UX.q('#setSelectAllButton').onclick=()=>{UX.syncSetSelection();UX.filteredSetQuestions().forEach(q=>UX.setSelection.add(UX.idOf(q)));UX.renderSetList();};UX.q('#setClearButton').onclick=()=>{UX.setSelection.clear();UX.renderSetList();};
  UX.setupSetFilters();
})();
