/* 독립 납기 달력: 현황 우선처리 영역에 직접 표시 */
const calStyle33=document.createElement('style');
calStyle33.textContent=`.due-calendar33{margin:0 0 18px;padding:14px;background:#fff;border:1px solid #d9e6df;border-radius:14px}.due-calendar33-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.due-calendar33-header strong{font-size:1.02rem}.due-calendar33-header button{border:1px solid #cbdcd3;background:#fff;color:#235342;border-radius:8px;padding:5px 10px;font:inherit}.due-calendar33-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:4px}.due-calendar33-week{text-align:center;color:#60766d;font-size:.72rem}.due-calendar33-cell{min-height:65px;border:1px solid #e0eae4;border-radius:8px;padding:4px}.due-calendar33-cell.blank{border:0}.due-calendar33-date{font-size:.75rem;font-weight:800;color:#597268}.due-calendar33-company{display:block;width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;border:0;background:#edf4f0;color:#235342;border-radius:5px;margin:3px 0 0;padding:3px;font:inherit;font-size:.67rem;text-align:left}.due-calendar33-company.late{background:#fff0ed;color:#b53f31}.due-calendar33-detail{margin:0 0 13px}.due-calendar33-detail h3{font-size:1rem;margin:8px 0}.due-calendar33-today{border-color:#235342;background:#f3f8f5}`;
document.head.append(calStyle33);
let calMonth33=null,calPick33=null,calRows33=[];
function drawCalendar33(){
 const box=$('#priorityList');if(!box)return;
 box.querySelectorAll('.due-calendar33,.due-calendar33-detail').forEach(x=>x.remove());
 const now=new Date(today()+'T00:00:00'),base=calMonth33?new Date(calMonth33+'T00:00:00'):now,first=new Date(base.getFullYear(),base.getMonth(),1),last=new Date(base.getFullYear(),base.getMonth()+1,0);
 calRows33=data.orders.flatMap(o=>(o.lines||[]).filter(l=>n(l.shipped)<n(l.quantity)).map(l=>({o,l,date:l.dueDate||o.dueDate}))).filter(x=>x.date);
 const groups={};calRows33.forEach((x,i)=>((groups[x.date]??={})[x.o.company]??=[]).push(i));
 let cells=[];for(let i=0;i<first.getDay();i++)cells.push('<div class="due-calendar33-cell blank"></div>');
 for(let d=1;d<=last.getDate();d++){const key=`${base.getFullYear()}-${String(base.getMonth()+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,companies=Object.keys(groups[key]||{}),late=key<=today();cells.push(`<div class="due-calendar33-cell ${key===today()?'due-calendar33-today':''}"><span class="due-calendar33-date">${d}</span>${companies.slice(0,2).map(c=>`<button type="button" class="due-calendar33-company ${late?'late':''}" data-calpick33="${key}|${encodeURIComponent(c)}">${esc(c)}</button>`).join('')}${companies.length>2?`<small>+${companies.length-2}개사</small>`:''}</div>`);}
 const calendar=`<section class="due-calendar33"><div class="due-calendar33-header"><button type="button" data-calnav33="-1">‹</button><strong>납기 달력 · ${base.getFullYear()}년 ${base.getMonth()+1}월</strong><button type="button" data-calnav33="1">›</button></div><div class="due-calendar33-grid">${['일','월','화','수','목','금','토'].map(x=>`<div class="due-calendar33-week">${x}</div>`).join('')}${cells.join('')}</div></section>`;
 box.insertAdjacentHTML('afterbegin',calendar);
 if(calPick33){const [date,encoded]=calPick33.split('|'),company=decodeURIComponent(encoded),rows=calRows33.filter(x=>x.date===date&&x.o.company===company);box.querySelector('.due-calendar33').insertAdjacentHTML('afterend',`<section class="due-calendar33-detail"><h3>${esc(date)} · ${esc(company)} 납기 상세</h3>${rows.map(x=>lineCard(x.o,x.l)).join('')}</section>`);}
}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-calnav33]'),pick=e.target.closest('[data-calpick33]');if(nav){const b=calMonth33?new Date(calMonth33+'T00:00:00'):new Date(today()+'T00:00:00');b.setMonth(b.getMonth()+n(nav.dataset.calnav33));calMonth33=`${b.getFullYear()}-${String(b.getMonth()+1).padStart(2,'0')}-01`;calPick33=null;drawCalendar33();}if(pick){calPick33=pick.dataset.calpick33;drawCalendar33();}});
const render33=render;render=()=>{render33();setTimeout(drawCalendar33,0)};setTimeout(drawCalendar33,0);
