/* 제품 기준 발주 역조회 + 중복 제품/발주 완전 삭제 */
const productOrderStyle26=document.createElement('style');
productOrderStyle26.textContent=`.product-order-link{display:block;width:100%;padding:10px 0;border:0;background:transparent;text-align:left;font:inherit;color:#173128}.product-order-link strong{display:block}.product-order-link span{display:block;margin-top:3px;color:#60766d;font-size:.84rem}.product-order-link:after{content:'발주 정보 보기 ›';display:block;margin-top:6px;color:#245b49;font-size:.83rem;font-weight:850}.classification-actions{display:flex;gap:7px;margin-top:8px}.classification-actions button{margin:0}.product-delete{border:1px solid #efb7ad!important;color:#b53f31!important}.product-orders-empty{font-size:.84rem;color:#60766d;margin:7px 0}.product-order-path{margin:0 0 10px;color:#60766d;font-size:.87rem}.product-order-period{margin:10px 0;border:1px solid #d9e6df;border-radius:11px;padding:10px}.product-order-period h3{margin:0 0 4px;font-size:1rem}.product-order-period p{margin:3px 0;color:#60766d;font-size:.86rem}`;
document.head.append(productOrderStyle26);
function productLines26(productId){return data.orders.flatMap(o=>o.lines.filter(l=>l.productId===productId).map(l=>({o,l})));}
function productOrderButton26(p){const count=productLines26(p.id).length;return count?`<button type="button" class="product-order-link" data-product-orders="${p.id}"><strong>${esc(p.spec)}</strong><span>${esc(p.name)} · 발주 ${count}건</span></button>`:`<div class="catalog-spec">${esc(p.spec)}<span class="product-orders-empty"> · 연결된 발주 없음</span></div>`;}
function openProductOrders26(productId){const p=data.products.find(x=>x.id===productId);if(!p)return;const rows=productLines26(productId);$('#productOrderTitle26').textContent=`${p.name} 발주 정보`;$('#productOrderBody26').innerHTML=`<p class="product-order-path">${esc(p.spec)} · 현재 공장 재고 ${q(stock(p))}${unit(p)}</p>${rows.length?rows.map(({o,l})=>`<section class="product-order-period"><h3>${esc(o.company)}</h3><p>발주기간: ${esc(o.orderDate||'미입력')} ${o.dueDate?`· 납기 ${esc(l.dueDate||o.dueDate)}`:''}</p>${lineCard(o,l)}</section>`).join(''):'<div class="empty">연결된 발주 정보가 없습니다.</div>'}`;show('#productOrderDialog26');}
function removeProduct26(productId){const p=data.products.find(x=>x.id===productId);if(!p)return;const related=data.orders.filter(o=>o.lines.some(l=>l.productId===productId));const title=`${p.name} · ${p.spec}`;if(!confirm(`${title} 제품을 삭제할까요?\n\n연결된 발주 ${related.length}건과 해당 생산·출고 기록도 함께 삭제됩니다.\n이 작업은 되돌릴 수 없습니다.`))return;data.orders=data.orders.filter(o=>!o.lines.some(l=>l.productId===productId));data.products=data.products.filter(x=>x.id!==productId);if(Array.isArray(data.history))data.history=data.history.filter(x=>x.productId!==productId);save();toast(`${title} 및 관련 발주 ${related.length}건을 삭제했습니다.`);}
function catalogHtml26(){const html=Object.entries(data.catalog).map(([code,x])=>`<details class="stock-group"><summary><span class="catalog-code">${esc(x.label)}</span><span class="order-meta">${Object.keys(x.types).length}개 종류</span></summary>${Object.entries(x.types).map(([kind,specs])=>`<div class="line-card"><div class="catalog-kind">${esc(kind)}</div>${specs.length?specs.map(spec=>{const ps=productsForCatalog22(code,kind,spec);return ps.length?ps.map(productOrderButton26).join(''):`<div class="catalog-spec">${esc(spec)}</div>`}).join(''):'<div class="catalog-spec">등록 규격 없음</div>'}<button type="button" class="catalog-empty-edit" data-catalog-edit="${code}|${encodeURIComponent(kind)}">종류·규격 관리</button></div>`).join('')}</details>`).join('');return `<section class="catalog-tools"><button type="button" class="primary" id="openCatalog">제품분류도 관리</button><p class="catalog-note">규격을 누르면 발주처 → 발주기간 → 발주 상세와 생산·출고 입력을 확인할 수 있습니다.</p>${html}</section>`;}
function classificationNeeded26(){const products=data.products.filter(needsClassification19);if(!products.length)return '<div class="empty">분류가 필요한 제품이 없습니다.</div>';return `<section class="classification-needed"><div class="classification-title"><h3>분류 필요 제품</h3><span class="classification-count">${products.length}개</span></div><p class="classification-help">중복 등록된 제품은 관련 발주까지 함께 삭제할 수 있습니다.</p><details class="stock-group" open><summary>제품 목록 보기 <span class="order-meta">${products.length}개</span></summary><div class="classification-list">${products.map(p=>`<article class="classification-card"><strong>${esc(p.name)} · ${esc(p.spec)}</strong><span class="classification-meta">${esc(p.code||'코드 미입력')} · ${esc(p.kind||'종류 미확정')} · ${unit(p)}</span><div class="classification-actions"><button type="button" class="small-action" data-edit-product="${p.id}">제품 정보 수정</button><button type="button" class="small-action product-delete" data-delete-product="${p.id}">삭제</button></div></article>`).join('')}</div></details></section>`;}
master=()=>catalogHtml26()+classificationNeeded26();
const stockList26=stockList;stockList=()=>{if(!data.products.length)return '<div class="empty">등록된 제품이 없습니다.</div>';const codes={};data.products.forEach(p=>{const code=code18(p),kind=inferKind18(p,code);((codes[code]??={})[kind]??=[]).push(p)});return Object.entries(codes).map(([code,kinds])=>`<details class="stock-group"><summary>${esc(group18(code))} <span class="order-meta">${Object.values(kinds).flat().length}개 제품</span></summary>${Object.entries(kinds).map(([kind,ps])=>`<details class="period"><summary>${esc(kind)} <span class="order-meta">${ps.length}개 규격</span></summary>${ps.map(p=>`<details class="line-card"><summary><strong>${esc(p.spec)}</strong><span class="stock-now ${stock(p)<=0?'urgent':''}">현재 총재고 ${q(stock(p))}${unit(p)}</span></summary><p class="muted">${esc(p.name)} · 코드 ${esc(p.code||'미입력')}</p><div class="numbers stock-detail"><div>초기재고<strong>${q(p.opening)}${unit(p)}</strong></div><div>누적 생산완료<strong>${q(p.produced)}${unit(p)}</strong></div><div>누적 출고<strong>${q(p.shipped)}${unit(p)}</strong></div><div>재고 조정<strong>${q(p.adjustment)}${unit(p)}</strong></div></div><button type="button" class="small-action" data-product-orders="${p.id}">발주 정보 보기</button><button class="small-action" data-adjust="${p.id}">재고 수정</button></details>`).join('')}</details>`).join('')}</details>`).join('');};
document.body.insertAdjacentHTML('beforeend',`<dialog id="productOrderDialog26" class="dialog"><div><div class="dialog-head"><h2 id="productOrderTitle26">제품 발주 정보</h2><button class="close" type="button" data-close>×</button></div><div id="productOrderBody26"></div></div></dialog>`);
document.addEventListener('click',e=>{const b=e.target.closest('[data-product-orders],[data-delete-product]');if(!b)return;if(b.dataset.productOrders)openProductOrders26(b.dataset.productOrders);if(b.dataset.deleteProduct)removeProduct26(b.dataset.deleteProduct);});
render();
