const ux=document.createElement('style');ux.textContent='.summary-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}.summary-card{padding:15px;background:#fff;border:1px solid #d9e6df;border-radius:15px}.summary-card span{display:block;color:#60766d;font-size:.82rem}.summary-card strong{display:block;font-size:1.4rem;margin-top:5px}.summary-card.alert{border-color:#efb7ad;background:#fff8f6}.summary-card.ok{border-color:#b8d9c5}.urgent{color:#b53f31;font-weight:850}.remove-complete{margin:10px 0;border:1px solid #e2b5ae;border-radius:9px;padding:8px 10px;background:#fff7f5;color:#a64034;font-weight:800}';document.head.append(ux);
let adjustProduct=null;
const originalStock=stock; stock=p=>originalStock(p)+n(p.adjustment);
function due(o){if(!o.dueDate)return {text:'납기 미입력',days:null};let d=Math.ceil((new Date(o.dueDate+'T00:00')-new Date(today()+'T00:00'))/86400000);return {text:d<0?`${Math.abs(d)}일 지연`:d===0?'D-day':`D-${d}`,days:d}}
function done(o){return o.lines.length>0&&o.lines.every(l=>n(l.shipped)>=n(l.quantity))}
function enhancedLine(o,l){let p=data.products.find(x=>x.id===l.productId)||product(l.name,l.spec,l.unit),left=n(l.quantity)-n(l.shipped);return `<article class="line-card"><h3>${esc(l.name)}</h3><p class="spec">${esc(l.spec)}</p><div class="numbers"><div>발주수량<strong>${q(l.quantity)}${l.unit}</strong></div><div>생산예정<strong>${q(l.planned)}${l.unit}</strong></div><div>생산완료<strong>${q(l.orderProduced)}${l.unit}</strong></div><div>발주 잔량<strong>${q(left)}${l.unit}</strong></div><div>공장 재고<strong>${q(stock(p))}${p.unit}</strong></div><div>출고 완료<strong>${q(l.shipped)}${l.unit}</strong></div></div><button data-line="${o.id}|${l.id}">생산 · 출고 입력</button></article>`}
function enhancedGroups(mode){let map={};for(let o of data.orders){if(mode==='dashboard'&&(o.hidden||done(o)))continue;(map[o.company]??=[]).push(o)}let entries=Object.entries(map);if(!entries.length)return '<div class="empty">표시할 진행 중 발주가 없습니다.</div>';return entries.map(([c,os])=>`<details><summary>${esc(c)} <span class="order-meta">${os.length}건</span></summary>${os.map(o=>{let x=due(o);return `<details class="period"><summary>${o.orderDate}${o.dueDate?` · 납기 ${o.dueDate}`:''} <span class="order-meta ${x.days!==null&&x.days<=7?'urgent':''}">${done(o)?'발주 완료':x.text} · ${o.lines.length}개 품목</span></summary>${o.memo?`<p class="muted">${esc(o.memo)}</p>`:''}${done(o)&&mode==='dashboard'?`<button class="remove-complete" data-hide-order="${o.id}">현황에서 제거</button>`:''}${o.lines.map(l=>enhancedLine(o,l)).join('')}</details>`}).join('')}</details>`).join('')}
function enhancedStock(){let m={};data.products.forEach(p=>(m[category(p)]??=[]).push(p));return Object.entries(m).map(([c,ps])=>`<details class="stock-group"><summary>${c} <span class="order-meta">${ps.length}개 제품</span></summary>${ps.map(p=>`<article class="line-card"><h3>${esc(p.name)}</h3><p class="spec">${esc(p.spec)}</p><div class="numbers"><div>초기재고<strong>${q(p.opening)}${p.unit}</strong></div><div>누적 생산완료<strong>${q(p.produced)}${p.unit}</strong></div><div>누적 출고<strong>${q(p.shipped)}${p.unit}</strong></div><div>재고 조정<strong>${q(p.adjustment)}${p.unit}</strong></div><div>현재 총재고<strong>${q(stock(p))}${p.unit}</strong></div></div><button data-adjust="${p.id}">재고 수정</button></article>`).join('')}</details>`).join('')||'<div class="empty">등록된 제품이 없습니다.</div>'}
const baseRender=render;render=()=>{baseRender();$('#dashboardGroups').innerHTML=enhancedGroups('dashboard');$('#orderGroups').innerHTML=enhancedGroups('orders');if(stockMode==='all')$('#inventoryContent').innerHTML=enhancedStock();let all=data.orders,urgent=all.filter(o=>!done(o)&&due(o).days!==null&&due(o).days<=7).length,active=all.filter(o=>!done(o)&&!o.hidden).length,short=data.products.filter(p=>stock(p)<0).length,ready=all.filter(o=>!done(o)&&o.lines.every(l=>{let p=data.products.find(x=>x.id===l.productId);return p&&stock(p)>=n(l.quantity)-n(l.shipped)})).length;$('#summaryCards').innerHTML=`<div class="summary-card ${urgent?'alert':''}"><span>납기 임박</span><strong>${urgent}건</strong></div><div class="summary-card"><span>처리 중 발주</span><strong>${active}건</strong></div><div class="summary-card ${short?'alert':''}"><span>재고 부족 품목</span><strong>${short}개</strong></div><div class="summary-card ok"><span>즉시 출고 가능</span><strong>${ready}건</strong></div>`};
document.addEventListener('click',e=>{let d=e.target.dataset;if(d.hideOrder!==undefined){if(confirm('정말 현황에서 제거하시겠습니까?\n발주 이력과 재고는 그대로 유지됩니다.')){data.orders.find(o=>o.id===d.hideOrder).hidden=true;save()}}if(d.adjust){adjustProduct=data.products.find(p=>p.id===d.adjust);$('#adjustInfo').textContent=`${adjustProduct.name} · ${adjustProduct.spec}\n현재 총재고 ${q(stock(adjustProduct))}${adjustProduct.unit}`;$('#actualStockInput').value=stock(adjustProduct);$('#adjustReasonInput').value='';show('#adjustDialog')}});
$('#adjustForm').onsubmit=e=>{e.preventDefault();let actual=n($('#actualStockInput').value);adjustProduct.adjustment=n(adjustProduct.adjustment)+(actual-stock(adjustProduct));adjustProduct.adjustReason=$('#adjustReasonInput').value;hide('#adjustDialog');save();toast('실제 재고로 수정했습니다.')};
render();
