const ui=document.createElement('style');ui.textContent=`.four{grid-template-columns:repeat(4,1fr)}.search{width:100%;padding:13px;border:1px solid #c8d9d0;border-radius:11px;font:inherit;margin:0 0 12px}.summary-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}.summary-card{padding:0;background:#fff;border:1px solid #d9e6df;border-radius:15px;text-align:left;overflow:hidden}.summary-card button{padding:15px;width:100%;border:0;background:transparent;text-align:left;font:inherit;color:inherit}.summary-card span{display:block;color:#60766d;font-size:.82rem}.summary-card strong{display:block;font-size:1.4rem;margin-top:5px}.summary-card.alert{border-color:#efb7ad;background:#fff8f6}.summary-card.ok{border-color:#b8d9c5}.urgent{color:#b53f31;font-weight:850}.stock-now{display:block!important;font-size:1.18rem!important;margin-top:7px}.line-card>summary{display:block!important;padding-right:32px;line-height:1.35}.line-card>summary .spec{display:block;margin-top:4px}.stock-detail{margin-top:10px}.small-action,.product-edit{margin:10px 0;border:1px solid #cbdcd3;border-radius:9px;padding:9px 11px;background:#fff;color:#235342;font-weight:800}.priority-title{margin:22px 0 8px;font-size:1.04rem}.priority-card{padding:13px 15px;background:#fff;border:1px solid #d9e6df;border-radius:13px;margin:7px 0}.priority-card strong{display:block}.priority-card span{font-size:.88rem;color:#60766d}.badge{display:inline-block;border-radius:999px;padding:3px 8px;background:#edf4f0;color:#225343;font-size:.78rem;font-weight:800}.badge.alert{background:#fff0ed;color:#b53f31}.status-text{color:#60766d;font-size:.9rem;font-weight:500}.summary-row{padding:12px 0;border-bottom:1px solid #e4ece7}.summary-row:last-child{border:0}.hidden{display:none!important}@media(max-width:430px){.four{gap:5px}.four .tab{padding:13px 3px;font-size:.93rem}}`;document.head.append(ui);
const rawStock=stock;stock=p=>rawStock(p)+n(p.adjustment);const unit=p=>p?.unit||'개';
function due(o){if(!o.dueDate)return{t:'납기 미입력',d:null};let d=Math.ceil((new Date(o.dueDate)-new Date(today()))/86400000);return{t:d<0?`${-d}일 지연`:d===0?'D-day':`D-${d}`,d}}function done(o){return o.lines.length&&o.lines.every(l=>n(l.shipped)>=n(l.quantity))}function label(o){let x=due(o);return done(o)?'':`<span class="badge ${x.d!==null&&x.d<=7?'alert':''}">${x.t}</span>`}
lineCard=(o,l)=>{let p=data.products.find(x=>x.id===l.productId)||product(l.name,l.spec,l.unit),left=n(l.quantity)-n(l.shipped);return `<article class="line-card"><h3>${esc(l.name)}</h3><p class="spec">${esc(l.spec)}${n(l.shipped)>=n(l.quantity)?' · <span class="status-text">발주 완료</span>':''}</p><div class="numbers"><div>발주수량<strong>${q(l.quantity)}${l.unit}</strong></div><div>생산예정<strong>${q(l.planned)}${l.unit}</strong></div><div>생산완료<strong>${q(l.orderProduced)}${l.unit}</strong></div><div>발주 잔량<strong>${q(left)}${l.unit}</strong></div><div>공장 재고<strong>${q(stock(p))}${p.unit}</strong></div><div>출고 완료<strong>${q(l.shipped)}${l.unit}</strong></div></div><button data-line="${o.id}|${l.id}">생산 · 출고 입력</button></article>`};
function orderHtml(o,dash=false){return `<details class="period"><summary><span>${o.orderDate}${o.dueDate?` · 납기 ${o.dueDate}`:''}</span> ${label(o)} <span class="order-meta">${o.lines.length}개 품목</span></summary>${o.memo?`<p class="muted">${esc(o.memo)}</p>`:''}${o.lines.map(l=>lineCard(o,l)).join('')}${dash&&done(o)?`<button class="small-action" data-hide-order="${o.id}">현황에서 숨기기</button>`:''}</details>`}
function groups13(mode){let map={};data.orders.forEach(o=>{if(mode==='dash'&&o.hidden)return;(map[o.company]??=[]).push(o)});let es=Object.entries(map).sort((a,b)=>a[0].localeCompare(b[0],'ko'));return es.length?es.map(([c,os])=>`<details><summary>${esc(c)} <span class="order-meta">${os.length}건</span></summary>${os.sort((a,b)=>(a.dueDate||'9999-12-31').localeCompare(b.dueDate||'9999-12-31')).map(o=>orderHtml(o,mode==='dash')).join('')}</details>`).join(''):'<div class="empty">표시할 발주가 없습니다.</div>'}
const cat=p=>p.category||category(p);function master(){let m={};data.products.forEach(p=>(m[cat(p)]??=[]).push(p));return Object.entries(m).map(([c,ps])=>`<details class="stock-group"><summary>${esc(c)} <span class="order-meta">${ps.length}개 제품</span>${c==='미분류·기타'?'<span class="badge alert">정리 필요</span>':''}</summary>${ps.map(p=>`<article class="line-card"><h3>${esc(p.name)}</h3><p class="spec">${esc(p.spec)}</p><p class="muted">코드 ${esc(p.code||'미입력')} · 단위 ${unit(p)}</p><button class="product-edit" data-edit-product="${p.id}">제품 정보 수정</button></article>`).join('')}</details>`).join('')}
function stockList(){let m={};data.products.forEach(p=>(m[cat(p)]??=[]).push(p));if(!data.products.length)return '<div class="empty">등록된 제품이 없습니다.</div>';return Object.entries(m).map(([c,ps])=>`<details class="stock-group"><summary>${esc(c)} <span class="order-meta">${ps.length}개 제품</span></summary>${ps.map(p=>{let h=(data.history||[]).filter(x=>x.productId===p.id).slice(0,5);return `<details class="line-card"><summary><strong>${esc(p.name)}</strong><span class="spec">${esc(p.spec)}</span><span class="stock-now ${stock(p)<=0?'urgent':''}">현재 총재고 ${q(stock(p))}${unit(p)}</span></summary><div class="numbers stock-detail"><div>초기재고<strong>${q(p.opening)}${unit(p)}</strong></div><div>누적 생산완료<strong>${q(p.produced)}${unit(p)}</strong></div><div>누적 출고<strong>${q(p.shipped)}${unit(p)}</strong></div><div>재고 조정<strong>${q(p.adjustment)}${unit(p)}</strong></div></div>${h.length?`<p class="muted">최근 입력<br>${h.map(x=>`${esc(x.at)} ${esc(x.text)}`).join('<br>')}</p>`:''}<button class="small-action" data-adjust="${p.id}">재고 수정</button></details>`}).join('')}</details>`).join('')}
function priority(){let os=data.orders.filter(o=>!done(o)&&!o.hidden).sort((a,b)=>(a.dueDate||'9999-12-31').localeCompare(b.dueDate||'9999-12-31')).slice(0,5);$('#priorityList').innerHTML=os.length?`<h3 class="priority-title">오늘 / 이번 주 우선 처리</h3>${os.map(o=>`<article class="priority-card"><strong>${esc(o.company)} · ${label(o)}</strong><span>${o.orderDate} 발주 · ${o.lines.length}개 품목${o.dueDate?` · 납기 ${o.dueDate}`:''}</span></article>`).join('')}<h3 class="priority-title">발주 현황</h3>`:'<h3 class="priority-title">발주 현황</h3>'}
const baseRender=render;render=()=>{baseRender();$('#dashboardGroups').innerHTML=groups13('dash');$('#orderGroups').innerHTML=groups13('order');$('#inventoryContent').innerHTML=stockMode==='all'?stockList():`<div class="groups">${groups13('order')}</div>`;$('#productContent').innerHTML=master();priority();let os=data.orders,urgent=os.filter(o=>!done(o)&&due(o).d!==null&&due(o).d<=7).length,active=os.filter(o=>!done(o)&&!o.hidden).length,short=data.products.filter(p=>stock(p)<=0).length,ready=os.flatMap(o=>o.lines).filter(l=>{let p=data.products.find(x=>x.id===l.productId);return n(l.quantity)>n(l.shipped)&&stock(p)>=n(l.quantity)-n(l.shipped)}).length;$('#summaryCards').innerHTML=`<div class="summary-card ${urgent?'alert':''}"><button data-summary="urgent"><span>납기 임박</span><strong>${urgent}건</strong></button></div><div class="summary-card"><button data-summary="active"><span>처리 중 발주</span><strong>${active}건</strong></button></div><div class="summary-card ${short?'alert':''}"><button data-summary="short"><span>재고 부족 품목</span><strong>${short}개</strong></button></div><div class="summary-card ok"><button data-summary="ready"><span>즉시 출고 가능</span><strong>${ready}건</strong></button></div>`};
function record(p,text){data.history??=[];data.history.unshift({at:new Date().toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}),productId:p.id,text});data.history=data.history.slice(0,5)}let undoTimer;function undo(before,msg){let t=$('#toast');clearTimeout(undoTimer);t.innerHTML=`${esc(msg)} <button id="undoNow" type="button">되돌리기</button>`;t.classList.remove('hidden');$('#undoNow').onclick=()=>{data=JSON.parse(before);save();toast('방금 입력을 되돌렸습니다.')};undoTimer=setTimeout(()=>t.classList.add('hidden'),5000)}
function saveLine13(e){e.preventDefault();let {l,p}=selectedLine,prod=n($('#producedInput').value),ship=n($('#shippedInput').value),planned=n($('#plannedInput').value);if(prod>planned)return toast('생산완료 수량은 생산예정 수량보다 클 수 없습니다.');if(ship>stock(p)+prod)return toast('공장 전체 재고보다 많이 출고할 수 없습니다.');if(ship>n(l.quantity)-n(l.shipped))return toast('발주수량보다 많이 출고할 수 없습니다.');let before=JSON.stringify(data),prev=stock(p);l.planned=planned-prod;l.orderProduced=n(l.orderProduced)+prod;p.produced=n(p.produced)+prod;p.shipped=n(p.shipped)+ship;l.shipped=n(l.shipped)+ship;if(prod)record(p,`${l.name} 생산완료 +${q(prod)}${l.unit}`);if(ship)record(p,`${selectedLine.o.company} 출고 -${q(ship)}${l.unit}`);hide('#lineDialog');save();undo(before,`${l.name} 재고: ${q(prev)}${unit(p)} → ${q(stock(p))}${unit(p)}`)}
function saveProduct13(e){e.preventDefault();let f=$('#productForm'),name=$('#productName').value.trim(),spec=$('#productSpec').value.trim(),pid=f.dataset.edit;if(!name||!spec)return;let p=pid?data.products.find(x=>x.id===pid):product(name,spec,$('#productUnit').value);p.name=name;p.spec=spec;p.code=$('#productCode').value.trim();p.category=$('#productCategory').value;p.unit=$('#productUnit').value;if(!pid)p.opening=n($('#openingStock').value);data.orders.forEach(o=>o.lines.forEach(l=>{if(l.productId===p.id){l.name=p.name;l.spec=p.spec;l.unit=p.unit}}));delete f.dataset.edit;hide('#productDialog');save();toast('제품 정보를 저장했습니다.')}
function openAdjust(id){let p=data.products.find(x=>x.id===id);$('#adjustForm').dataset.product=id;$('#adjustInfo').textContent=`${p.name} · 현재 ${q(stock(p))}${unit(p)}`;$('#actualStockInput').value=stock(p);$('#adjustReasonInput').value='';show('#adjustDialog')}function adjust(e){e.preventDefault();let p=data.products.find(x=>x.id===$('#adjustForm').dataset.product),actual=n($('#actualStockInput').value),before=JSON.stringify(data),prev=stock(p);p.adjustment=n(p.adjustment)+(actual-prev);record(p,`${$('#adjustReasonInput').value.trim()||'실사 재고 조정'} ${q(prev)}${unit(p)} → ${q(actual)}${unit(p)}`);hide('#adjustDialog');save();undo(before,`${p.name} 재고: ${q(prev)}${unit(p)} → ${q(actual)}${unit(p)}`)}
function openSummary(type){let os=data.orders,rows=[],title='';if(type==='urgent'){title='납기 임박';rows=os.filter(o=>!done(o)&&due(o).d!==null&&due(o).d<=7).map(o=>`${o.company} · ${due(o).t} · 납기 ${o.dueDate}`)}if(type==='active'){title='처리 중 발주';rows=os.filter(o=>!done(o)&&!o.hidden).map(o=>`${o.company} · ${o.lines.length}개 품목 · ${o.dueDate?`납기 ${o.dueDate}`:'납기 미입력'}`)}if(type==='short'){title='재고 부족 품목';rows=data.products.filter(p=>stock(p)<=0).map(p=>`${p.name} · ${p.spec} · 현재 ${q(stock(p))}${unit(p)}`)}if(type==='ready'){title='즉시 출고 가능';rows=os.flatMap(o=>o.lines.filter(l=>{let p=data.products.find(x=>x.id===l.productId);return n(l.quantity)>n(l.shipped)&&stock(p)>=n(l.quantity)-n(l.shipped)}).map(l=>`${o.company} · ${l.name} · 출고 가능 ${q(n(l.quantity)-n(l.shipped))}${l.unit}`))}$('#summaryTitle').textContent=title;$('#summaryList').innerHTML=rows.length?rows.map(x=>`<div class="summary-row">${esc(x)}</div>`).join(''):'<div class="empty">해당 항목이 없습니다.</div>';show('#summaryDialog')}
function filter(box,q){$$(box+' > details').forEach(x=>x.classList.toggle('hidden',!!q&&!x.innerText.toLowerCase().includes(q.toLowerCase())))}$('#lineForm').onsubmit=saveLine13;$('#productForm').onsubmit=saveProduct13;$('#adjustForm').onsubmit=adjust;document.addEventListener('click',e=>{let d=e.target.closest('[data-summary],[data-edit-product],[data-adjust],[data-hide-order]')?.dataset||e.target.dataset;if(e.target.id==='newProduct'){let f=$('#productForm');f.reset();delete f.dataset.edit;$('#openingStock').value='0'}if(d.summary)openSummary(d.summary);if(d.editProduct){let p=data.products.find(x=>x.id===d.editProduct),f=$('#productForm');f.dataset.edit=p.id;$('#productName').value=p.name;$('#productSpec').value=p.spec;$('#productCode').value=p.code||'';$('#productCategory').value=p.category||'미분류·기타';$('#productUnit').value=p.unit;$('#openingStock').value=p.opening;show('#productDialog')}if(d.adjust)openAdjust(d.adjust);if(d.hideOrder){let o=data.orders.find(x=>x.id===d.hideOrder);if(confirm(`${o.company} 발주를 현황에서 숨길까요?\n발주 기록과 재고에는 영향을 주지 않습니다.`)){o.hidden=true;save();toast('현황에서 숨겼습니다.')}}});[['dashboardSearch','#dashboardGroups'],['orderSearch','#orderGroups'],['inventorySearch','#inventoryContent'],['productSearch','#productContent']].forEach(([id,box])=>{let e=$('#'+id);if(e)e.oninput=()=>filter(box,e.value)});render();
/* 개인용 안전장치: 단위·출고·중복 제품·빠른 보기 */
const extra=document.createElement('style');extra.textContent=`.quick-filters{display:flex;gap:7px;flex-wrap:wrap;margin:-3px 0 13px}.quick-filters button{padding:8px 10px;border:1px solid #cbdcd3;border-radius:999px;background:#fff;color:#235342;font:inherit;font-size:.86rem}.quick-filters button.active{background:#123c39;color:#fff;border-color:#123c39}.plan-box{padding:13px 15px;border:1px solid #d9e6df;border-radius:13px;background:#fff;margin:7px 0}.plan-box strong{display:block}.plan-box span{display:block;color:#60766d;font-size:.88rem;margin-top:4px}.link-button{margin-left:7px;border:0;background:transparent;color:#235342;text-decoration:underline;font:inherit;font-size:.85rem}.warn-note{font-size:.85rem;color:#b53f31;margin:8px 0}`;document.head.append(extra);
function lineState(o,l){let p=data.products.find(x=>x.id===l.productId),need=n(l.quantity)-n(l.shipped),s=stock(p);return s>=need?'재고 있음':n(l.planned)>0?'생산예정 있음':'계획 필요'}
function todayPlan(){let ls=data.orders.flatMap(o=>o.lines.map(l=>({o,l}))).filter(x=>n(x.l.planned)>0);return ls.length?`<h3 class="priority-title">오늘 생산 예정</h3>${ls.map(({o,l})=>`<article class="plan-box"><strong>${esc(l.name)} · ${q(l.planned)}${l.unit}</strong><span>${esc(o.company)} · ${esc(l.spec)}</span></article>`).join('')}`:''}
const oldPriority=priority;priority=()=>{oldPriority();$('#priorityList').insertAdjacentHTML('afterbegin',todayPlan())};
const oldLineCard=lineCard;lineCard=(o,l)=>oldLineCard(o,l).replace('</p><div class="numbers">',` · <span class="status-text">${lineState(o,l)}</span></p><div class="numbers">`);
const oldMaster=master;master=()=>oldMaster().replace(/<button class="product-edit" data-edit-product="([^"]+)">제품 정보 수정<\/button>/g,'<button class="product-edit" data-edit-product="$1">제품 정보 수정</button><button class="link-button" data-link-product="$1">기존 제품과 연결</button>');
const oldSaveProduct=saveProduct13;saveProduct13=e=>{let f=$('#productForm'),pid=f.dataset.edit,p=pid&&data.products.find(x=>x.id===pid),next=$('#productUnit').value;if(p&&p.unit!==next&&!confirm(`${p.name}의 단위를 ${p.unit}에서 ${next}로 바꿀까요?\n기존 발주 수량 표기도 함께 바뀝니다.`))return e.preventDefault();oldSaveProduct(e)};$('#productForm').onsubmit=saveProduct13;
document.body.insertAdjacentHTML('beforeend','<dialog id="linkDialog" class="dialog"><form id="linkForm"><div class="dialog-head"><h2>기존 제품과 연결</h2><button class="close" type="button" data-close>×</button></div><p id="linkSource" class="info"></p><label>연결할 기존 제품<select id="linkTarget"></select></label><p class="warn-note">두 제품의 재고와 발주 기록을 하나로 합칩니다.</p><div class="actions"><button class="secondary" type="button" data-close>취소</button><button class="primary" type="submit">연결</button></div></form></dialog>');
function linkDialog(id){let p=data.products.find(x=>x.id===id),options=data.products.filter(x=>x.id!==id).map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.spec)} (${x.unit})</option>`).join('');if(!options)return toast('연결할 기존 제품이 없습니다.');let d=$('#linkDialog');$('#linkSource').textContent=`${p.name} · ${p.spec}`;$('#linkTarget').innerHTML=options;d.dataset.source=id;show('#linkDialog')}
$('#linkForm').onsubmit=e=>{e.preventDefault();let source=data.products.find(p=>p.id===$('#linkDialog').dataset.source),target=data.products.find(p=>p.id===$('#linkTarget').value);if(source.unit!==target.unit)return toast(`단위가 달라 연결할 수 없습니다. (${source.unit} / ${target.unit})`);if(!confirm(`${source.name}을 ${target.name}에 연결할까요?\n재고와 기존 발주가 합쳐집니다.`))return;target.opening=n(target.opening)+n(source.opening);target.produced=n(target.produced)+n(source.produced);target.shipped=n(target.shipped)+n(source.shipped);target.adjustment=n(target.adjustment)+n(source.adjustment);data.orders.forEach(o=>o.lines.forEach(l=>{if(l.productId===source.id){l.productId=target.id;l.name=target.name;l.spec=target.spec;l.unit=target.unit}}));data.products=data.products.filter(p=>p.id!==source.id);hide('#linkDialog');save();toast('기존 제품에 연결했습니다.')};
function quickFilters(){[['dashboardSearch','dashboardGroups'],['orderSearch','orderGroups'],['inventorySearch','inventoryContent']].forEach(([sid,bid])=>{let search=$('#'+sid);if(!search||search.previousElementSibling?.classList.contains('quick-filters'))return;let box=document.createElement('div');box.className='quick-filters';let defs=sid==='inventorySearch'?[['low','재고 부족만']]:[['soon','납기 7일 이내'],['plan','계획 필요만']];defs.forEach(([key,text])=>{let b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=()=>{b.classList.toggle('active');let on=b.classList.contains('active');if(!on){render();return}let q=key==='low'?'현재 총재고':key==='soon'?'D-':'';if(key==='soon'){let cards=$$('#'+bid+' details');cards.forEach(x=>{let t=x.innerText;let m=t.match(/D-(\d+)/);x.classList.toggle('hidden',!(m&&n(m[1])<=7))})}else if(key==='plan'){let cards=$$('#'+bid+' .line-card');cards.forEach(x=>x.classList.toggle('hidden',!x.innerText.includes('계획 필요')))}else{let cards=$$('#'+bid+' .line-card');cards.forEach(x=>x.classList.toggle('hidden',!x.innerText.includes('현재 총재고 0')))}};box.append(b)});search.before(box)})}
document.addEventListener('click',e=>{let id=e.target.dataset.linkProduct;if(id)linkDialog(id)});const r14=render;render=()=>{r14();quickFilters()};render();
const oldSafeLine=saveLine13;saveLine13=e=>{let ship=n($('#shippedInput').value);if(ship&&selectedLine&&!confirm(`${selectedLine.o.company} 발주에 ${selectedLine.l.name} ${q(ship)}${selectedLine.l.unit}를 출고 처리할까요?`)){e.preventDefault();return}oldSafeLine(e)};$('#lineForm').onsubmit=saveLine13;
/* 빠른 필터는 부모 묶음을 숨기지 않고, 해당 발주만 다시 표시한다. */
function groupedOrders(os,onlyPlan=false){let m={};os.forEach(o=>{let lines=onlyPlan?o.lines.filter(l=>lineState(o,l)==='계획 필요'):o.lines;if(lines.length)(m[o.company]??=[]).push({...o,lines})});let es=Object.entries(m);return es.length?es.map(([c,orders])=>`<details open><summary>${esc(c)} <span class="order-meta">${orders.length}건</span></summary>${orders.map(o=>orderHtml(o)).join('')}</details>`).join(''):'<div class="empty">해당 발주가 없습니다.</div>'}
function lowStockHtml(){let ps=data.products.filter(p=>stock(p)<=0);if(!ps.length)return '<div class="empty">재고 부족 제품이 없습니다.</div>';return `<details class="stock-group" open><summary>재고 부족 품목 <span class="order-meta">${ps.length}개 제품</span></summary>${ps.map(p=>`<details class="line-card" open><summary><strong>${esc(p.name)}</strong><span class="spec">${esc(p.spec)}</span><span class="stock-now urgent">현재 총재고 ${q(stock(p))}${unit(p)}</span></summary><div class="numbers stock-detail"><div>초기재고<strong>${q(p.opening)}${unit(p)}</strong></div><div>누적 생산완료<strong>${q(p.produced)}${unit(p)}</strong></div><div>누적 출고<strong>${q(p.shipped)}${unit(p)}</strong></div></div><button class="small-action" data-adjust="${p.id}">재고 수정</button></details>`).join('')}</details>`}
function quickFiltersV2(){[['dashboardSearch','dashboardGroups'],['orderSearch','orderGroups'],['inventorySearch','inventoryContent']].forEach(([sid,bid])=>{let search=$('#'+sid);if(!search)return;search.parentElement.querySelectorAll('.quick-filters').forEach(x=>x.remove());let box=document.createElement('div');box.className='quick-filters';let defs=sid==='inventorySearch'?[['low','재고 부족만']]:[['soon','납기 7일 이내'],['plan','생산 계획 필요']];defs.forEach(([key,text])=>{let b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=()=>{if(b.classList.contains('active')){render();return}if(key==='soon'){$('#'+bid).innerHTML=groupedOrders(data.orders.filter(o=>!done(o)&&due(o).d!==null&&due(o).d<=7))}else if(key==='plan'){$('#'+bid).innerHTML=groupedOrders(data.orders.filter(o=>!done(o)&&o.lines.some(l=>lineState(o,l)==='계획 필요')),true)}else{stockMode='all';$$('.subtab').forEach(x=>x.classList.toggle('active',x.dataset.stockMode==='all'));$('#'+bid).innerHTML=lowStockHtml()}box.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))};box.append(b)});search.before(box)})}
const r15=render;render=()=>{r15();quickFiltersV2()};render();
/* 발주 잔량 기준 부족 계산: 납기 빠른 발주부터 공장 재고를 배정한다. */
function orderGaps(){let available={};data.products.forEach(p=>available[p.id]=Math.max(0,stock(p)));let rows=[];data.orders.filter(o=>!done(o)).sort((a,b)=>(a.dueDate||'9999-12-31').localeCompare(b.dueDate||'9999-12-31')).forEach(o=>o.lines.forEach(l=>{let remain=Math.max(0,n(l.quantity)-n(l.shipped)),have=Math.min(remain,available[l.productId]??0),short=Math.max(0,remain-have);available[l.productId]=Math.max(0,(available[l.productId]??0)-have);rows.push({o,l,remain,short,planGap:Math.max(0,short-n(l.planned))})}));return rows}
const oldOpenSummary=openSummary;openSummary=type=>{if(type!=='short')return oldOpenSummary(type);let rows=orderGaps().filter(x=>x.short>0);$('#summaryTitle').textContent='재고 부족 품목';$('#summaryList').innerHTML=rows.length?rows.map(x=>`<div class="summary-row">${esc(x.o.company)} · ${esc(x.l.name)} · 발주 잔량 ${q(x.remain)}${x.l.unit} · 재고 ${q(x.remain-x.short)}${x.l.unit} · <strong class="urgent">${q(x.short)}${x.l.unit} 부족</strong></div>`).join(''):'<div class="empty">발주 잔량을 기준으로 재고가 부족한 품목이 없습니다.</div>';show('#summaryDialog')};
function lowOrderHtml(){let rows=orderGaps().filter(x=>x.short>0);if(!rows.length)return '<div class="empty">발주 잔량을 기준으로 재고가 부족한 품목이 없습니다.</div>';return `<details class="stock-group" open><summary>발주 잔량 기준 재고 부족 <span class="order-meta">${rows.length}건</span></summary>${rows.map(x=>`<article class="line-card"><h3>${esc(x.l.name)}</h3><p class="spec">${esc(x.o.company)} · ${esc(x.l.spec)}</p><div class="numbers"><div>발주 잔량<strong>${q(x.remain)}${x.l.unit}</strong></div><div>공장 재고 배정<strong>${q(x.remain-x.short)}${x.l.unit}</strong></div><div>부족 수량<strong class="urgent">${q(x.short)}${x.l.unit}</strong></div><div>생산예정<strong>${q(x.l.planned)}${x.l.unit}</strong></div></div></article>`).join('')}</details>`}
function planOrderHtml(){let rows=orderGaps().filter(x=>x.planGap>0);if(!rows.length)return '<div class="empty">추가 생산계획이 필요한 발주가 없습니다.</div>';return `<details class="stock-group" open><summary>생산 계획 필요 <span class="order-meta">${rows.length}건</span></summary>${rows.map(x=>`<article class="line-card"><h3>${esc(x.l.name)}</h3><p class="spec">${esc(x.o.company)} · ${esc(x.l.spec)}</p><div class="numbers"><div>재고 부족<strong>${q(x.short)}${x.l.unit}</strong></div><div>생산예정<strong>${q(x.l.planned)}${x.l.unit}</strong></div><div>추가 계획 필요<strong class="urgent">${q(x.planGap)}${x.l.unit}</strong></div></div><button data-line="${x.o.id}|${x.l.id}">생산 · 출고 입력</button></article>`).join('')}</details>`}
function quickFiltersV3(){[['dashboardSearch','dashboardGroups'],['orderSearch','orderGroups'],['inventorySearch','inventoryContent']].forEach(([sid,bid])=>{let search=$('#'+sid);if(!search)return;search.parentElement.querySelectorAll('.quick-filters').forEach(x=>x.remove());let box=document.createElement('div');box.className='quick-filters';let defs=sid==='inventorySearch'?[['low','발주 잔량 부족만']]:[['soon','납기 7일 이내'],['plan','생산 계획 필요']];defs.forEach(([key,text])=>{let b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=()=>{if(b.classList.contains('active'))return render();if(key==='soon')$('#'+bid).innerHTML=groupedOrders(data.orders.filter(o=>!done(o)&&due(o).d!==null&&due(o).d<=7));else if(key==='plan')$('#'+bid).innerHTML=planOrderHtml();else{$('#'+bid).innerHTML=lowOrderHtml()}box.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))};box.append(b)});search.before(box)})}
const r16=render;render=()=>{r16();let short=orderGaps().filter(x=>x.short>0).length,el=$('[data-summary="short"]');if(el){el.parentElement.classList.toggle('alert',!!short);el.innerHTML=`<span>발주 잔량 부족</span><strong>${short}건</strong>`}quickFiltersV3()};render();
const fieldScript=document.createElement('script');fieldScript.async=false;fieldScript.src='enhance-v14.js?rev=2';document.body.append(fieldScript);
const openingScript=document.createElement('script');openingScript.async=false;openingScript.src='enhance-v15.js?rev=2';document.body.append(openingScript);

const editScript=document.createElement('script');editScript.async=false;editScript.src='enhance-v16.js?rev=2';document.body.append(editScript);

const groupingScript=document.createElement('script');groupingScript.async=false;groupingScript.src='enhance-v17.js?rev=1';document.body.append(groupingScript);

const taxonomyScript=document.createElement('script');taxonomyScript.async=false;taxonomyScript.src='enhance-v18.js?rev=2';document.body.append(taxonomyScript);

const finalFixScript=document.createElement('script');
finalFixScript.async=false;
finalFixScript.src='enhance-v19.js?rev=1';
document.body.append(finalFixScript);

const perLineDueScript=document.createElement('script');
perLineDueScript.async=false;
perLineDueScript.src='enhance-v20.js?rev=1';
document.body.append(perLineDueScript);

const dueCleanupScript=document.createElement('script');
dueCleanupScript.async=false;
dueCleanupScript.src='enhance-v21.js?rev=1';
document.body.append(dueCleanupScript);

const catalogDirectEditScript=document.createElement('script');
catalogDirectEditScript.async=false;
catalogDirectEditScript.src='enhance-v22.js?rev=1';
document.body.append(catalogDirectEditScript);
