const $=s=>document.querySelector(s);const store={get:(k,d)=>JSON.parse(localStorage.getItem('toeic-mald'+k)||JSON.stringify(d)),set:(k,v)=>localStorage.setItem('toeic-mald'+k,JSON.stringify(v))};let items=[],queue=[],i=0,mode='',cancel=false;
const shuffle=a=>[...a].sort(()=>Math.random()-.5);const key=q=>q.part+'|'+q.ko+'|'+q.en;
function boot(){items=window.TOEIC_SENTENCES||[];$('#status').textContent=`Part 2~5 · ${items.length}문장`;const parts=[...new Set(items.map(x=>x.part))];$('#parts').innerHTML=parts.map(p=>`<button class="mode" data-part="${p}"><strong>${p}</strong><span>${items.filter(x=>x.part===p).length}문장 훈련</span></button>`).join('');stats()}
function stats(){const log=store.get('log',{}),all=Object.values(log);$('#done').textContent=all.filter(x=>x==='done').length;$('#reviewCount').textContent=all.filter(x=>x==='maybe'||x==='wrong').length;$('#spoken').textContent=store.get('spoken',0).toLocaleString()}
function start(m,list){if(!list.length)return alert('재훈련할 문장이 없습니다.');mode=m;queue=m==='all'?shuffle(list):[...list];i=0;$('#home').classList.add('hidden');$('#study').classList.remove('hidden');$('#label').textContent=({memorize:'암기 모드',test:'시험 모드',review:'재훈련',all:'전체 랜덤'})[m]||m;$('#audio').classList.toggle('hidden',m==='test');$('#testTools').classList.toggle('hidden',m!=='test');render()}
function render(){cancel=true;speechSynthesis.cancel();cancel=false;const q=queue[i];$('#part').textContent=q.part;$('#korean').textContent=q.ko;$('#english').textContent=q.en;$('#english').classList.toggle('hidden',mode==='test');$('#answer').textContent=q.en;$('#answer').classList.add('hidden');$('#showAnswer').textContent='정답 보기';$('#bar').style.width=`${i/queue.length*100}%`;$('#voice').textContent=`${i+1} / ${queue.length}`}
function speak(){const q=queue[i];if(cancel)return;$('#voice').textContent='재생 중';const text=q.en.replace(/_+/g,'blank').replace(/[가-힣]+/g,'blank');const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=Number($('#rate').value);u.onend=()=>{if(!cancel)$('#voice').textContent='재생 완료'};speechSynthesis.speak(u)}
function mark(v){store.set('log',{...store.get('log',{}),[key(queue[i])]:v});store.set('spoken',store.get('spoken',0)+1);stats();$('#voice').textContent=v==='done'?'암기 완료':'재훈련에 저장됨'}
document.addEventListener('click',e=>{const p=e.target.closest('[data-part]')?.dataset.part,m=e.target.closest('[data-mode]')?.dataset.mode;if(p)start('memorize',items.filter(x=>x.part===p));if(m){const log=store.get('log',{});start(m,m==='review'?items.filter(x=>['maybe','wrong'].includes(log[key(x)])):items)}const r=e.target.closest('[data-result]')?.dataset.result;if(r)mark(r)});$('#play').onclick=()=>{speechSynthesis.cancel();cancel=false;speak()};$('#stop').onclick=()=>{cancel=true;speechSynthesis.cancel();$('#voice').textContent='중지됨'};$('#showAnswer').onclick=()=>{$('#answer').classList.toggle('hidden');const shown=!$('#answer').classList.contains('hidden');$('#showAnswer').textContent=shown?'정답 숨기기':'정답 보기';if(shown){$('#audio').classList.remove('hidden');$('#voice').textContent='정답 음성을 들을 수 있습니다.'}};$('#next').onclick=()=>{if(++i>=queue.length){alert('이번 세트를 마쳤습니다.');i=0;if(mode==='all')queue=shuffle(queue)}render()};$('#back').onclick=()=>{cancel=true;speechSynthesis.cancel();$('#study').classList.add('hidden');$('#home').classList.remove('hidden');stats()};$('#reset').onclick=()=>{if(confirm('이 기기의 토스 진도를 모두 초기화할까요?')){localStorage.clear();stats()}};boot();
